### ISSUE TITLE
objFiles is empty

### ISSUE THREAD

**Issue by Dwgjjdxq** [astrolagrange/GPU-based-feature-adaptive-rendering-of-Loop-subdivision-surfaces#1]
Thank you for your source code. When I compile your project, there are some errors in the input. That is the Media file should have a file about "objFiles/icosahedron.obj". cloud you share your objFiles?  Thank you so much.

My Email: dwgjjdxq@gmail.com

**Comment by pxiangwu** [comment]
I just corrected this error and added the obj file.
